Revert "gralloc: Fix integer overflow in roundUpToPageSize"
* Build error without this revert:
In file included from hardware/qcom/display/gralloc/gr_utils.h:34:
vendor/qcom/opensource/commonsys-intf/display/gralloc/gralloc_priv.h:77:38:
error: implicit conversion changes signedness: 'int' to 'unsigned int' [-Werror,-Wsign-conversion]
  return (x + (getpagesize() - 1)) & ~(getpagesize() - 1);

This reverts commit dbf678a61552ae94e104177853f32309eb9b5088.

Change-Id: If792fbc07b2d3a37f0fecf87c4c923b9148455e9